version: "3.8"

services:
  client1:
    build:
      context: .
      dockerfile: Dockerfile-cliente
    environment:
      - SERVER_HOST=host.docker.internal
      - SERVER_PORT=5000
      - CLIENT_ID=1

  client2:
    build:
      context: .
      dockerfile: Dockerfile-cliente
    environment:
      - SERVER_HOST=host.docker.internal
      - SERVER_PORT=5001
      - CLIENT_ID=2

  client3:
    build:
      context: .
      dockerfile: Dockerfile-cliente
    environment:
      - SERVER_HOST=host.docker.internal
      - SERVER_PORT=5002
      - CLIENT_ID=3

  client4:
    build:
      context: .
      dockerfile: Dockerfile-cliente
    environment:
      - SERVER_HOST=host.docker.internal
      - SERVER_PORT=5003
      - CLIENT_ID=4

  client5:
    build:
      context: .
      dockerfile: Dockerfile-cliente
    environment:
      - SERVER_HOST=host.docker.internal
      - SERVER_PORT=5004
      - CLIENT_ID=5
